### PR TITLE
Fix for Issue #173

### PR DESCRIPTION
**Pull request by wangmiao1981**
Issue #173 is due to missing multiple lines support in the regular expression match.

To enable the multiple lines support, I add "(?s)" option. 

Unit tested 
res1 = String
Vector(1
, 2
)

res2 = String
Vector(1
, 2
, 3
)

I add two test cases in the test scala file.

### CODE REVIEW

**Comment by chipsenkbeil** [comment]
I'm seeing this error:

```
should convert to success with result output if no failure *** FAILED *** (672 milliseconds)
[info]     The code passed to eventually never returned normally. Attempted 1 times over 555.6627950000001 milliseconds. Last failure message: None.get. (BrokerTransformerSpec.scala:41)
```

**Comment by wangmiao1981** [comment]
After rebase, it passes the test.

**Comment by chipsenkbeil** [comment]
Awesome. Will review and verify tomorrow.

**Comment by chipsenkbeil** [comment]
Your master branch works for me, although I am a little confused why Github indicates that only the tests are showing up as changes in the PR.

**Comment by chipsenkbeil** [comment]
Oh, it's because this was the code that you checked into master. Okay, well, going to merge this to add the additional tests.

**Pull request merged**
