### PR TITLE
Properly close sockets on system shutdown.

### LINKED ISSUE #194: actor system does not shut down gracefully
When you call shutdown on KernelBootstrap there are threads that remain running and prevent the process from ending. 

screen shot 2015-11-04 at 3 51 37 pm

here's a thread dump of the 2 categories that seem to be lingering: 
"iothread-2@7680" prio=5 tid=0x8d nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at sun.nio.ch.KQueueArrayWrapper.kevent0(KQueueArrayWrapper.java:-1)
	  at sun.nio.ch.KQueueArrayWrapper.poll(KQueueArrayWrapper.java:200)
	  at sun.nio.ch.KQueueSelectorImpl.doSelect(KQueueSelectorImpl.java:103)
	  at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:87)
	  - locked <0x2642> (a sun.nio.ch.KQueueSelectorImpl)
	  - locked <0x2643> (a java.util.Collections$UnmodifiableSet)
	  - locked <0x2644> (a sun.nio.ch.Util$2)
	  at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:98)
	  at zmq.Poller.run(Poller.java:207)
	  at java.lang.Thread.run(Thread.java:745)

"reaper-1@7679" prio=5 tid=0x8c nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at sun.nio.ch.KQueueArrayWrapper.kevent0(KQueueArrayWrapper.java:-1)
	  at sun.nio.ch.KQueueArrayWrapper.poll(KQueueArrayWrapper.java:200)
	  at sun.nio.ch.KQueueSelectorImpl.doSelect(KQueueSelectorImpl.java:103)
	  at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:87)
	  - locked <0x2645> (a sun.nio.ch.KQueueSelectorImpl)
	  - locked <0x2646> (a java.util.Collections$UnmodifiableSet)
	  - locked <0x2647> (a sun.nio.ch.Util$2)
	  at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:98)
	  at zmq.Poller.run(Poller.java:207)
	  at java.lang.Thread.run(Thread.java:745)

I suppose it's possible some zmq socket is not getting closed properly on shutdown. Has anyone been able to successfully shutdown the kernel before and actually end all the related threads? I'm currently experimenting with running more than one kernel in the same jvm and these lingering threads are really annoying.

### PR DESCRIPTION
**Pull request by jodersky**
Fixes #194 

Also, only catch exceptions (errors should kill the JVM)

### CODE REVIEW

**Comment by jodersky** [comment]
> No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself.

retesting...

**Comment by chipsenkbeil** [comment]
@jodersky, this is a known issue with our tests. In reality, the "system" tests need to be redone in a different manner. Unfortunately, the only option (as you have probably seen) is to just rerun the tests.

**Comment by chipsenkbeil** [comment]
Hm, this might be something different. Seems to regularly fail with those errors. Have you or @Lull3rSkat3r run all of the tests locally? Seems odd that fixing shutdown would cause hanging.

**Comment by jodersky** [comment]
arghh, running tests locally never terminates. Its strange because termination worked without an issue when ending a packed kernel deployment. I'll check this out tomorrow

**Comment by jodersky** [comment]
I managed to narrow the issue down, something in `system.KernelCommSpecForSystem` never terminates

**Comment by jodersky** [comment]
There was already the functionality present to close contexts when sockets were closed, however the contexts were never registered.

**Comment by jodersky** [comment]
There are still some issues so I'm changing this PR to a work-in-progress until I fix it

**Comment by jodersky** [comment]
It should work now

**Comment by jodersky** [comment]
@chipsenkbeil, everything should be ok now

**Comment by chipsenkbeil** [comment]
@jodersky, awesome. Will review and verify tomorrow.

**Comment by chipsenkbeil** [comment]
LGTM

**Pull request merged**
