### PR TITLE
Cleaning up README and updating Makefile to ease dev experience.

### PR DESCRIPTION
**Pull request by lbustelo**
This PR is an attempt of simplify the instructions to get up an going with development on Spark Kernel.

### CODE REVIEW

**Comment by chipsenkbeil** [comment]
It looks like the list on the readme under overview is not being rendered correctly. I think you need a space between your paragraph and the list (starting with `1.`), but not quite sure without trying it myself.

You can view the current appearance [here](https://github.com/ibm-et/spark-kernel/tree/UpdateDevExperience).

If you don't change it, I can get to it later.

**Comment by lbustelo** [comment]
I'll change it. It is WIP. Thanks 

Gino B.

**Comment by lbustelo** [comment]
I've fixed the numbered list

**Comment by lbustelo** [comment]
I removed the WIP... @wellecks will go over the steps and if it looks good, merge it.

**Comment by wellecks** [comment]
Looks good - the README is clear and the steps worked. I fixed some minor typos, looks good to merge.

**Pull request merged**
