### PR TITLE
Add new interpreters

### PR DESCRIPTION
**Pull request by chipsenkbeil**
Adds PySpark, SparkR, and Spark SQL interpreters along with new, extensible broker interface.

### CODE REVIEW

**Comment by chipsenkbeil** [comment]
Missed a bad rebase file (wrong import). Going to update and push changes after local tests pass again.

**Comment by chipsenkbeil** [comment]
As @lbustelo brought to my attention, we need to update quite a bit of documentation regarding how to use these interpreters. Furthermore, we need large disclaimers on these interpreters as they are all experimental and there are obvious changes in architecture that need to be made: magics are only accessible in Scala, using the magic form of SparkR dumps out our logging in the SparkR runner, bootstrapping has become incredibly complicated, etc.

**Comment by nimbusgo** [comment]
As an extension to this it's possible to have multiple interpreters of the same language but with different namespaces.

I was able to do a rough demo of this for just pyspark here: https://github.com/ibm-et/spark-kernel/commit/7ca77756fc925a6f9c3ee48b36a6c4b78f4f6249 

Basically, it allows uses like this:

-----------------------
%%Pyspark bob
<bob's python code>
-----------------------
%%Pyspark sally
<sally's python code>
-----------------------
%%Pyspark bob
<more ofbob's python code>
-----------------------

and the code is executed in separate interpreters. Using a namespace for the first time would create a new interpreter, using it again would use the appropriate existing interpreter. It would also make sense to add a new line magic to delete interpreters (if someone wants to restart for example).

This is just a rough demo that I did yesterday to see if it would work (it appears to). I'll add more details about the motivation for this in an issue soon.

**Comment by Bonsanto** [comment]
I have no idea how to use them :|

**Comment by chipsenkbeil** [comment]
@Bonsanto, we still need to go through and update a lot of our documentation. For now, you can use `%%pyspark some code` to run code via PySpark. Same for other interpreters via `%%scala`, `%%sparkr`, and `%%sql`. The three new interpreters are highly experimental and using other magics with the interpreters is currently not supported.

If you want to change the default interpreter from Scala, you can start the Spark Kernel with either the environment variable `DEFAULT_INTERPRETER` or the command line option `--default-interpreter` and provide _scala_, _pyspark_, _sparkr_, or _sql_.

**Pull request merged**
