### PR TITLE
Small Makefile improvements

### PR DESCRIPTION
**Pull request by nicerobot**
Removed unneeded shell calls and utilize immediate assignment instead of lazy.

### CODE REVIEW

**Comment by lbustelo** [comment]
This is more in line with what I wanted to do for #230. 

@nicerobot We are in the middle of moving the project into https://github.com/apache/incubator-toree. As part of the contribution I would need to know if you've signed the https://www.apache.org/licenses/icla.txt.

**Comment by wellecks** [comment]
LGTM, I ran `make dev` and `make dist` in POSIX mode successfully

In terms of #230, this PR fixes the issue but also includes an additional `build-info` command

**Comment by wellecks** [comment]
LGTM, I ran `make dev` and `make dist` in POSIX mode successfully, and also successfully built the Dockerfile that @lbustelo referenced in #230 

Note that this PR includes a `build-info` make target in addition to the fixes necessary for #230

**Comment by lbustelo** [comment]
@nicerobot Thanks for that. Just bear with me for a couple of days here. We are in the middle of this migration into a different git repo managed by Apache. Still don't have a clear answer on how to I validate your signature and take the contribution.

**Comment by lresende** [comment]
Thanks, PR Merged into the Apache repository.

**Comment by lbustelo** [comment]
@nicerobot  your code is now here https://git-wip-us.apache.org/repos/asf?p=incubator-toree.git

**Pull request closed without merging**
