### PR TITLE
Add on successful completion

### PR DESCRIPTION
**Pull request by Lull3rSkat3r**
@rcsenkbeil and @swelleck, looking for thoughts on this before we merge it. I have updated the DocumentationExamples.scala class to include example usage.

### CODE REVIEW

**Comment by Lull3rSkat3r** [comment]
This pull request is for #45

**Comment by wellecks** [comment]
Looks good to me

**Comment by rcsenkbeil** [comment]
@Lull3rSkat3r, so we don't want a blanket API for "finished either way"?

**Comment by Lull3rSkat3r** [comment]
I have updated the `onSuccessfulCompletion` method to be `onSuccess` and it will take and `ExecuteReplyOk` as an option. This will make for a more symmetrical API when handling error and success cases.

**Pull request merged**
