### PR TITLE
Build interpreter classpath based on Classloader hierarchy

### LINKED ISSUE #216: ScalaInterpreter only work when the kernel assembly jar is on the root classloader
The code in [SparkInterpreter.scala](https://github.com/ibm-et/spark-kernel/blob/ecfa5dd2abe8f992e54b12f4c5e411855b72e898/scala-interpreter/src/main/scala/com/ibm/spark/kernel/interpreter/scala/ScalaInterpreter.scala#L197) does not get all the necesary jars if our assembly jar is not on the system classloader. The reason we are working now is because in [bin/spark-kernel](https://github.com/ibm-et/spark-kernel/blob/ecfa5dd2abe8f992e54b12f4c5e411855b72e898/etc/bin/spark-kernel#L35) we are adding our assembly jar to `--driver-class-path`. When using `--driver-class-path` our assembly is places in the `-cp` of the `java` command alongside the spark libs. In this setup, when the list of jars is assembled to give to SparkIMain, it contains all the jars (ours and spark's) and all is good.

This setup is not idea. It is causing issues with EclairJS. The ideal would be for extra jars to use the `jars` option to add themself to the context and to the classpath. The problem with using `-jars` and our current setup is that our classes are in the system classloader and the classes for `-jars` are in a child classloader. When we try to load interpreters, we cannot find any classes whose jar is added using `-jars`.

To solve this problem, we need to fix our issue in  [SparkInterpreter.scala](https://github.com/ibm-et/spark-kernel/blob/ecfa5dd2abe8f992e54b12f4c5e411855b72e898/scala-interpreter/src/main/scala/com/ibm/spark/kernel/interpreter/scala/ScalaInterpreter.scala#L197). The code for generating the list of Jars to give to SparkIMain needs to walk the Classloader hierarchy. That way we  can get rid of the unnecessary `--driver-class-path` in  [bin/spark-kernel](https://github.com/ibm-et/spark-kernel/blob/ecfa5dd2abe8f992e54b12f4c5e411855b72e898/etc/bin/spark-kernel#L35).

Once this is in place, we already proved that out assembly jar and others added through `-jars` will be on the same classloader.

### PR DESCRIPTION
**Pull request by lbustelo**
Fixes #216

I was able to remove the redundant addition of our assembly jar to `--driver-class-path` and get the kernel to run.

### CODE REVIEW

**Comment by lbustelo** [comment]
@bpburns Give this a try and see if it solves the problem with EclairJS.

@chipsenkbeil I ended up using the approach of walking up the classloader hierarchy. I did noticed that there are some extra entries in the classpath that are coming from the root classloader and they include jars that come from the jre path. It did not seem to do any harm with the tests that I ran. 

These are the classpath items
screen shot 2015-12-02 at 5 40 12 pm

These are the classloaders in the hierarchy.
screen shot 2015-12-02 at 5 40 49 pm

I like the classloader hierarchy walking approach because it seems more general than the code that I saw in [SparkILoop](https://github.com/apache/spark/blob/d83c2f9f0b08d6d5d369d9fae04cdb15448e7f0d/repl/scala-2.10/src/main/scala/org/apache/spark/repl/SparkILoop.scala#L199). SparkILoop seems to be explicitly picking the `java.class.path` property and then adding to it from a variety of config setting variables (i.e. `--jars, and others). Seems to me more error prone.

**Comment by bpburns** [comment]
This is working.  I was able to load the EclairJS interpreter jar with --jars.

**Comment by lbustelo** [comment]
Ran through https://github.com/jupyter/docker-demo-images/blob/master/notebooks/Welcome%20to%20Spark%20with%20Scala.ipynb and all worked fine.

**Comment by chipsenkbeil** [comment]
LGTM. Tested on local and standalone modes running on a Mac. Also tested on Linux.

**Pull request merged**
