### PR TITLE
dont truncate interpreter output based on magic %truncation and %showtypes

### PR DESCRIPTION
**Pull request by Lull3rSkat3r**

### CODE REVIEW

**Comment by pberkland** [comment]
This is for https://github.com/ibm-et/spark-kernel/issues/89

**Comment by rcsenkbeil** [comment]
Looks like you guys are causing a test suite to fail due to more than one Spark Context being initialized.

**Comment by Lull3rSkat3r** [comment]
We also need to add the license headers to the new files.

**Comment by cjm5325** [comment]
Looks good! :clap:

**Pull request merged**
