### PR TITLE
Removed code that was adding jar to conf... no longer needed

### LINKED ISSUE #224: Assembly jar added to cluster many times on startup
screen shot 2015-12-03 at 9 42 47 am

This is due to old code that added the jar of each module:
https://github.com/ibm-et/spark-kernel/blob/master/kernel/src/main/scala/com/ibm/spark/kernel/api/Kernel.scala#L442

Now, we should only need to add the jar once since all modules for the kernel are in the assembly jar. Furthermore, as mentioned by @lbustelo, Spark Submit might add the jar for us, so this code might not be necessary anymore. We need to verify that.

### PR DESCRIPTION
**Pull request by lbustelo**
fixes #224

### CODE REVIEW

**Comment by lbustelo** [comment]
I basically removed the code that was explicitly adding the jar to the conf. It seems that the new way of running the kernel through `spark-submit` already takes care of this. You can see in this screenshot that the jar is added.

screen shot 2015-12-08 at 9 23 06 am

@chipsenkbeil Can you please take a look at this?

**Comment by chipsenkbeil** [comment]
@lbustelo, you need to update the _KernelSpec_ to not test that we add jars anymore. Those tests are failing on Travis since we don't have that logic now.

**Comment by lbustelo** [comment]
@chipsenkbeil done

**Comment by chipsenkbeil** [comment]
LGTM

**Pull request merged**
